---
output:
  pdf_document:
    latex_engine: pdflatex
    keep_tex: false
geometry: "left=1.22in,right=1.22in,top=0.8in,bottom=0.8in"
header-includes:
  - \usepackage{array}
  - \usepackage{latexsym}
  - \usepackage{titlesec}
  - \usepackage{marvosym}
  - \usepackage{enumitem}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyfoot{}
  - \renewcommand{\headrulewidth}{0pt}
  - \renewcommand{\footrulewidth}{0pt}
  - \urlstyle{rm}
  - \raggedbottom
  - \raggedright
  - \setlength{\tabcolsep}{0in}
  - \titleformat{\section}{\vspace{-10pt}\scshape\raggedright\large}{}{0em}{}[\color{black}\titlerule \vspace{-6pt}]
---

\begin{tabular*}{\textwidth}{l@{\extracolsep{\fill}}r}
  \textbf{{\LARGE Thomas Gareau-Paquette}} & Email: \href{mailto:tg454@cornell.edu}{tg454@cornell.edu}\\
  \href{https://thomasgp.com}{thomasgp.com} & \textbf{{Last updated: `r format(Sys.time(), '%B %Y')`}}\\
\end{tabular*}

\vspace{1pt}

# Education

\begin{itemize}[leftmargin=*]
  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Cornell University} & Ithaca, NY \\
      \textit{Ph.D. -- Government} & \textit{Sept. 2024 -- Present} \\
    \end{tabular*}\vspace{-5pt}
      {\scriptsize \textit{ \footnotesize{\newline{}\textbf{Major Subfield:} American Politics}}}
      {\scriptsize \textit{ \footnotesize{\newline{}\textbf{Minor Subfields:} Comparative Politics \& Methods}}}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{McGill University} & Montréal, Canada \\
      \textit{Master of Arts -- Political Science; GPA: 4.00/4.00} & \textit{Sept. 2022 -- August 2024} \\
    \end{tabular*}\vspace{-5pt}
      {\scriptsize \textit{ \footnotesize{\newline{}\textbf{MA Thesis:}
      Higher Education, Higher Stakes: Education's Role in Shaping Redistribution Preferences and Vote Choice in Canada.}}}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{University of Michigan} & Ann Arbor, USA \\
      \textit{ICPSR Summer Program -- Political Science} & \textit{July 2023 -- Aug. 2023} \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Université de Montréal} & Montréal, Canada \\
      \textit{Bachelor of Science -- Political Science (Hons.); GPA: 4.28/4.3} & \textit{Sept. 2019 -- June 2022} \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{University of Washington} & Seattle, USA \\
      \textit{Killam Fellow (Fulbright) -- Political Science and Political Behavior; GPA: 3.97/4.00} & \textit{March 2022 -- June 2022} \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Université de Montréal} & Montréal, Canada \\
      \textit{Undergraduate Microprogram (15 credits) -- Big Data Analysis; GPA: 4.2/4.3} & \textit{Sept. 2021 -- April 2022} \\
    \end{tabular*}\vspace{-5pt}
\end{itemize}

\vspace{1pt}

# Research Experience \& Internships

\begin{itemize}[leftmargin=*]
  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Cornell University} & Ithaca, NY \\
      \textit{Graduate Research Assistant, Prof. Suzanne Mettler,} & \textit{November 2024 -- Present} \\
      \textit{Prof. Peter Enns, and Dean of CAS Peter Loewen} & \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Université Laval} & Montréal, Canada \\
      \textit{Graduate Research Assistant, Prof. Valérie-Anne Mahéo} & \textit{September 2022 -- October 2024} \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{McGill University} & Montréal, Canada \\
      \textit{Graduate Research Assistant, Prof. Dietlind Stolle} & \textit{May 2023 -- August 2024} \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{WZB -- Berlin Social Science Center} & Berlin, Germany (remote) \\
      \textit{Coder (Manifesto Project)} & \textit{September 2022 -- August 2024} \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Université de Sherbrooke} & Sherbrooke, Canada \\
      \textit{Quantitative Research Assistant, Prof. Jean-François Daoust} & \textit{January 2021 -- July 2024} \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{McGill University} & Montréal, Canada \\
      \textit{Quantitative Research and Teaching Assistant, Prof. Éric Bélanger} & \textit{June 2022 -- April 2023} \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{ENAP} & Montréal, Canada \\
      \textit{Quantitative Research Assistant, Research Chair on the} & \textit{April 2021 -- Dec. 2022} \\
      \textit{Evaluation of Public Policies for Vulnerable Populations} & \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Université de Montréal} & Montréal, Canada \\
      \textit{Quantitative Research Assistant, Canada Research Chair in Electoral Democracy} & \textit{October 2021 -- May 2022} \\
    \end{tabular*}\vspace{-5pt}

  \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{CIDEP Consultants} & Montréal, Canada \\
      \textit{Business Analyst Intern} & \textit{Jan. 2021 -- May 2021} \\
    \end{tabular*}\vspace{-5pt}
\end{itemize}

\vspace{1pt}

# Peer-Reviewed Publications

\vspace{1pt}

\begin{description}

    \item[] Daoust, J.-F., \& \textbf{Gareau-Paquette, T.} (2025). De plus en plus inquiets : qui sont les Québécois qui considèrent le français comme menacé et quelles en sont les conséquences électorales? \textit{Canadian Journal of Political Science/Revue Canadienne de science politique} (FirstView, 1--20).\\
    \textit{\small [Increasingly Worried: Who Are the Quebecers Who Consider French to Be Threatened and What Are the Electoral Consequences?]}

    \item[] Bélanger, É., Mongrain, P., \textbf{Gareau-Paquette, T.}, \& Mahéo, V.A. (2025). A Party that Went Viral? The Drivers of Support for the Parti Conservateur du Québec in the 2022 Election. \textit{Canadian Journal of Political Science/Revue Canadienne de science politique}, 58(2), 277--296.

    \item[] \textbf{Gareau-Paquette, T.}, \& Daoust, J.-F. (2024). Géographie politique de l'opinion publique québécoise et réévaluation du ``mystère'' de Québec. \textit{Canadian Journal of Political Science/Revue Canadienne de science politique}, 57(4), 816--841.\\
    \textit{\small [Political Geography of Québec Public Opinion and Reassessment of the ``Mystery'' of Québec City]}

    \item[] Daoust, J.-F., \& \textbf{Gareau-Paquette, T.} (2024). How Attitudes Toward Independence Reshaped Scottish Elections: A Longitudinal Analysis (1999--2021). \textit{Nations and Nationalism}.

    \item[] \textbf{Gareau-Paquette, T.}, Léal, A., Leblanc, J., Taylor, M., Vandewalle, V., \& Dassonneville, R. (2024). Voting for Women in Recent Canadian Elections. \textit{French Politics}, 22(1), 45--63.

    \item[] Daoust, J.-F., \& \textbf{Gareau-Paquette, T.} (2023). Is Quebec Independence Still Key in Making Sense of Canadian Elections? A Longitudinal Analysis (2000--2021). \textit{Regional \& Federal Studies}, 1--26.

\end{description}

\vspace{1pt}

# Other Publications

\subsection*{Book Review}
\begin{description}
    \item[] \textbf{Gareau-Paquette, T.} (2025). Political Engagement in Canadian City Elections. R. Michael McGregor and Laura B. Stephenson. 2024. Montreal: McGill-Queen's University Press, pp. 276. \textit{Canadian Journal of Political Science/Revue Canadienne de science politique}, 58(1), 255--257.
\end{description}

\subsection*{Newspaper Article/Op-Ed}
\begin{description}
    \item[] \textbf{Gareau-Paquette, T.}, \& Stolle, D. (2023, October 31). Dans certains pays européens, il existe un décalage notable entre un important soutien gouvernemental à l'Ukraine et une opinion publique plus ambivalente. \textit{Le Monde}.
\end{description}

\subsection*{Reports}
\begin{description}
    \item[] Mahéo, V.A., \& \textbf{Gareau-Paquette, T.} (2024, November 20). Résultats préliminaires de la première vague de sondages administrée en 2024 sur les activités collectives du Volet 2 du Programme d'Accueil et d'Intégration des Immigrants et la pleine participation au Québec. Fiche annuelle \#2. \textit{Ministère de l'Immigration, de la Francisation et de l'Intégration}.

    \item[] Mahéo, V.A., \& \textbf{Gareau-Paquette, T.} (2023, October 19). Résultats préliminaires de la première vague de sondages administrée en 2023 sur les activités collectives du Volet 2 du Programme d'Accueil et d'Intégration des Immigrants et la pleine participation au Québec. Fiche annuelle \#1. \textit{Ministère de l'Immigration, de la Francisation et de l'Intégration}.
\end{description}

\subsection*{Replication Studies}
\begin{description}
    \item[] Hicks, J., Bondi, A., \textbf{Gareau-Paquette, T.}, \& Patterson, S. (2024). Reproducing Do Policymakers Listen to Experts? Evidence from a National Survey of Local and State Policymakers (Lee 2022). \textit{I4R Discussion Paper Series}, No. 186.
\end{description}

\subsection*{R Packages}
\begin{description}
    \item[] \textbf{Gareau-Paquette, T.} (2023). qesR: Easy Access to All Quebec Election Studies Datasets. [R package version]. Available at: \url{https://github.com/ThomasGareau/qesR}.
\end{description}

\vspace{1pt}

# Research Projects (Selected)

\begin{description}

\item[] \textbf{Gareau-Paquette, T.}, Lucas, J., \& Loewen, P. \textit{Studying the Correlates of Vote Choice in Small Democracies}.

\item[] Stolle, D., \textbf{Gareau-Paquette, T.}, \& Harell, A. \textit{From Local to Global: Assessing European Solidarity through the Lens of Ukraine Aid}. Preprint.

\item[] Jabbour, A., Cakir, S., Coulombe, M., Fréchet, N., \textbf{Gareau-Paquette, T.}, Leblanc, J., Liang, B., Pautonnier, V., Rafie, T., Taylor, M., Vandewalle, V., Bergeron, M., Kostelka, F., \& Dassonneville, R. \textit{Do Political Surveys Overestimate Affective Polarization? Evidence From Germany and the United States}. Revise and Resubmit.

\item[] Bélanger, E., \& \textbf{Gareau-Paquette, T.} \textit{The 2022 Quebec Provincial Elections}.

\item[] Daoust, J.-F., \& \textbf{Gareau-Paquette, T.} \textit{The Politics of Language and Public Opinion in Quebec}.

\item[] \textbf{Gareau-Paquette, T.}, \& Jacques, O. \textit{The House Always Wins? Housing Affordability and Party Politics in Nine Post-Industrial Democracies}.

\item[] Enns, P., \& \textbf{Gareau-Paquette, T.} \textit{Forecasting the 2026 Midterms}.

\item[] Mahéo, V.A., \& \textbf{Gareau-Paquette, T.} \textit{Participating in Integration Activities and Participating in Quebec Society: A Study of Integration Programs and their Policy Feedback Effects}.

\item[] \textbf{Gareau-Paquette, T.}, \& Stolle, D. \textit{Linking Europe's Aid to Public Support towards Ukraine}.

\end{description}

\vspace{1pt}

# Presentations (Selected)

\begin{itemize}[leftmargin=*]

\item\small{\textbf{``Participating in Integration Activities and Participating in Quebec Society: A Study of Integration Programs and their Policy Feedback Effects.''}{: American Political Science Association, Vancouver, BC, Canada, 2025. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Higher Education, Higher Stakes: Education's Role in Shaping Redistribution Preferences and Vote Choice.''}{: American Political Science Association, Philadelphia, PA, USA, September 6th, 2024. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Higher Education, Higher Stakes: Education's Role in Shaping Redistribution Preferences and Vote Choice in Canada.''}{: CSDC McGill Lab, Montréal, Québec, Canada, June 17, 2024. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Les régionalismes au Québec.''}{: La participation démocratique au Québec et au Canada à l'étude, Sherbrooke, Québec, Canada, June 11th, 2024. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Higher Education, Higher Stakes: Education's Role in Shaping Redistribution Preferences and Vote Choice in Canada.''}{: CSDC Graduate Students Conference, Québec City, Québec, Canada, March 22, 2024. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Can Contacts with Public Services Foster Political Integration? A Study of New Immigrants' Experiences and their Attitudes.''}{: Midwest Political Science Association, Chicago, IL, USA, April 6th, 2024. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Recent Immigrants' Experiences with Integration Services: An Assessment of Access to Services across the Province.''}{: Pathways to Prosperity National Conference, Montréal, Québec, Canada, Nov. 20, 2023. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Regionalism(s) and Vote Choice in Quebec.''}{: Canada Research Chair in Electoral Democracy Weekly Seminar (UdeM), Montréal, Québec, Canada, Sept. 17, 2023. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Regionalism(s) and Political Behaviour in Quebec.''}{: CSDC McGill Lab, Montréal, Québec, Canada, Sept. 17, 2023. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Regionalism(s) in Quebec: Analyzing Citizens' Attitudes and Voting Behaviour.''}{: APSA Annual Meeting, Los Angeles, California, USA, August 31st --- Sept. 3, 2023. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``The Making of a `Super Issue': A Longitudinal Analysis of Attitudes Toward Scotland's Independence.''}{: APSA Annual Meeting, Los Angeles, California, USA, August 31st --- Sept. 3, 2023. \vspace{-2pt}}}
\vspace{2pt}
\item\small{Chair -- Governance and Provincial Politics / La gouvernance et la politique provinciale. CPSA Annual Meeting, Toronto, Ontario, Canada, May 30 --- June 1st, 2023. \vspace{-2pt}}
\vspace{2pt}
\item\small{\textbf{``Out of the Blue? The Drivers of Support for the Parti Conservateur du Québec in the 2022 Election.''}{: CPSA Annual Meeting, Toronto, Ontario, Canada, May 30 --- June 1st, 2023. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``The Making of a `Super Issue': A Longitudinal Analysis of Attitudes Toward Scotland's Independence.''}{: CPSA Annual Meeting, Toronto, Ontario, Canada, May 30 --- June 1st, 2023. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Reassessing The Effect of Political Trust on Vote Choice in Canada: A Longitudinal Perspective (2000--2021).''}{: CSDC Student Conference, Québec, Québec, Canada, March 31, 2023. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``How Stable Are Key Political Values and Beliefs of Canadian Voters?''}{: APSA Annual Meeting, Montréal, Québec, Canada, September 15--18, 2022. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``How Stable are Citizens' Attitudes toward Independence and Who Changes Their Minds? A Longitudinal Study of Scotland and Québec.''}{: CPSA Annual Conference, Montréal, Québec, Canada, May 30 --- June 3, 2022. \vspace{-2pt}}}
\vspace{2pt}
\item\small{\textbf{``Gender Affinity Voting in Recent Canadian Elections.''}{: Political Studies Association's Undergraduate Conference, University of York, York, United Kingdom, April 8, 2022. \vspace{-2pt}}}

\end{itemize}

\vspace{-5pt}

# Honors and Awards

\begin{description}[font=$\bullet$]

\item {Canada Graduate Scholarship (CGS-D) -- \textbf{SSHRC} -- 2025 (120,000\$ CAD)}

\item {Bourse de doctorat en recherche (secteur société et culture) -- \textbf{FRQSC} -- 2025 (100,000\$ CAD)}

\item {Kohut Fellowship -- \textbf{Roper Center} -- 2025 (5,000\$)}

\item {IES Graduate Research Grant -- \textbf{Einaudi Center, Cornell University} -- 2025 (4,000\$)}

\item {Co-Funding for Research Stay -- \textbf{Cluster of Excellence ``The Politics of Inequality,'' University of Konstanz} -- 2025 (3,000\$)}

\item {Conference Travel Grant -- \textbf{Cornell University} -- 2024 (400\$)}

\item {Sage Fellowship -- \textbf{Cornell University} -- 2024 (55,000\$)}

\item {Best Political Science Cumulative GPA Award [2019--2022 Cohort] -- \textbf{Université de Montréal} -- 2023 (1,000\$)}
\item {Travel Grant (conferences) -- \textbf{CECD} -- 2023 (1,000\$)}
\item {ICPSR Methodological Training Grant -- \textbf{CECD} -- 2023 (3,000\$)}
\vspace{1pt}
\item {Master's Training Scholarship -- \textbf{FRQSC} -- 2023--2024 (20,000\$)}
\vspace{1pt}
\item {Canada Graduate Scholarship (CGS-M) -- \textbf{SSHRC} -- 2022--2023 (17,500\$)}
\vspace{1pt}
\item {Eren Graduate Recruitment Fellowship -- \textbf{McGill University} -- 2022--2023 (5,000\$)}
\vspace{1pt}
\item {Centre for the Study of Democratic Citizenship Entrance Stipend -- \textbf{McGill University} -- 2022--2023 (2,500\$)}
\vspace{1pt}
\item {Ontario Graduate Scholarship (Masters) -- \textbf{University of Toronto} -- 2022--2023 (15,000\$) [Declined]}
\vspace{1pt}
\item {SPS Summer Academy Scholarship -- \textbf{European University Institute} -- 2022 (800\$)}
\vspace{1pt}
\item {Fulbright Cultural Awareness -- \textbf{Fulbright Canada} -- 2021--2022 (8,000\$)}
\vspace{1pt}
\item {Killam Fellowship -- \textbf{Fulbright Canada} -- 2021--2022 (8,000\$)}
\vspace{1pt}
\item {Jeunes Démocrates Tournament -- \textbf{Quebec National Assembly} -- 2015, 2017, 2018 (850\$)}

\end{description}

\vspace{1pt}

# Peer Reviewing

\vspace{1pt}

\begin{itemize}[leftmargin=0.4cm]
\item \textit{British Journal of Political Science (BJPOLS)}
\item \textit{Canadian Journal of Political Science (CJPS)}
\item \textit{Journal of Elections, Public Opinion \& Parties (JEPOP)}
\item \textit{West European Politics (WEP)}
\end{itemize}

\vspace{1pt}

# Service

\begin{itemize}[leftmargin=*]

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Cornell University, Department of Government} & Ithaca, NY \\
      \textit{Graduate Student Representative (American Politics Subfield)} & \textit{2025 -- Present} \\
    \end{tabular*}\vspace{-5pt}

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Cornell University} & Ithaca, NY \\
      \textit{Public Policy Minor Coordinator / Crime, Prisons, Education} & \textit{2025 -- Present} \\
      \textit{and Justice Minor Coordinator} & \\
    \end{tabular*}\vspace{-5pt}

\end{itemize}

\vspace{1pt}

# Volunteering Experiences (Academia)

\begin{itemize}[leftmargin=*]

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Revue Possibles} & Montréal, Canada \\
      \textit{Corrector} & \textit{April 2022 -- Present} \\
    \end{tabular*}\vspace{-5pt}

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Montreal Replication Games} & Montréal, Canada \\
      \textit{Replicator} & \textit{August 2023} \\
    \end{tabular*}\vspace{-5pt}

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{London Politica} & London, United Kingdom (remote) \\
      \textit{Lead Editor for North America} & \textit{Sept. 2021 -- July 2023} \\
    \end{tabular*}\vspace{-5pt}

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Foundation for International Understanding Through Students} & Seattle, WA \\
      \textit{Mentor} & \textit{March 2022 -- June 2022} \\
    \end{tabular*}\vspace{-5pt}

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Comité des Affaires Internationales de l'Université de Montréal} & Montréal, Canada \\
      \textit{Vice President (Innovation) and Staff Writer} & \textit{October 2019 -- April 2022} \\
    \end{tabular*}\vspace{-5pt}

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Passerelle+ Program} & Montréal, Canada \\
      \textit{Mentor} & \textit{September 2020 -- December 2022} \\
    \end{tabular*}\vspace{-5pt}

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{CISM 89.3} & Montréal, Canada \\
      \textit{Radio Host -- Cent Digressions} & \textit{Jan. 2021 -- Sept. 2021} \\
    \end{tabular*}\vspace{-5pt}

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Newspective} & New York, USA (remote) \\
      \textit{Deputy World News Editor} & \textit{April 2020 -- Sept. 2021} \\
    \end{tabular*}\vspace{-5pt}

    \vspace{-1pt}\item
    \begin{tabular*}{0.97\textwidth}{@{}p{0.67\textwidth}@{\extracolsep{\fill}}>{\raggedleft\arraybackslash}p{0.27\textwidth}@{}}
      \textbf{Délégation des Nations Unies de l'Université de Montréal} & Montréal, Canada \\
      \textit{Member} & \textit{Sept. 2019 -- April 2020} \\
    \end{tabular*}\vspace{-5pt}

\end{itemize}

\vspace{1pt}

# Additional Training

\begin{description}[font=$\bullet$]
\item {SPS Summer Academy on (In)Equality in Europe -- \textbf{European University Institute}, September 2022}
\vspace{-5pt}
\item {Introduction to Python -- \textbf{Datacamp}, December 2021}
\vspace{-5pt}
\item {Causal Inference with R -- \textbf{Datacamp}, August 2021}
\vspace{-5pt}
\item {Introduction to Causal Inference -- \textbf{ICPSR Short Workshops (remote)}, July 2021}
\vspace{-5pt}
\item {Introduction to Git and Github -- \textbf{Coursera \& Google}, June 2021}
\vspace{-5pt}
\item {Securing Digital Democracy -- \textbf{Coursera \& University of Michigan}, July 2020}
\end{description}

\vspace{1pt}

# Skills

\begin{itemize}[leftmargin=*]
\item\small{\textbf{Programming}{: R, Git, \LaTeX{} (Advanced); JavaScript, C, Python (Beginner) \vspace{-2pt}}}
\vspace{1pt}
\item\small{\textbf{Languages}{: English, French (Advanced), Italian (Beginner), German (Beginner)}}
\end{itemize}
